sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: iGeb7tz5IwaCaGNFfG8P5Q3zP2bHmLOgcn3bYO/TLNTTH6bXbq7aQGhE1sg/2S894MrS2yFzhmgQJf9h56H6V7abQIJOXStHwQFcNcYcNP5pY5D/GpEoLPShx03ddcwlsXwULLjvngwuB5Ip7GbZEHjXqirFZ4EDSfua70PQEKmvXPUoPbWcPpIDalE1J+bvxHbd9ELRAdCKgdN5T1OpeIzKDJs04vMq+26ulT9KXET1TwXfTa+Chj4hMxWSLUb787bDEGmTbUFZbartq+WKC6BKcbf6n7M1th8izfRzeliq6q7CCbPHhiE2Sl+R8yQUmIFaW9ual0/ay3dnNGErAj6m/cbpWTcsAKNU/wVGF7ymBm2wEtRdLYKzrTmFWSrfMgSCQzU7K8lS2hPL4GNt8HafB1c58sgqk+CGi5ZilDYu8ICGXZzjjHI+77+pwTnZVCla7Dl+XMRq2EoUwJp7X6iJhTh2QC48hMWY9iOryWAekZNl83RrqwBwbTjI92L6vN/HqIP4OxusRyyeI0YhoV5HKD07KVa0VtHijvOx/HFneaG9lkYkf9URrBSw+ouDz+2OFdUpYkqLMSMLYwLJHyjgVX/IreUsnlReqMEJrQKa2KCLd81oVWKqfy/MyBtBKJqpeixoOdgmcJxnhenI5bQhcBhgYaq+JFWJGg02VEY=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Celt-and-Saxon-Volume-2_4490
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy